runtime: go112

env_variables:
  PLATFORM: appengine
  # GIN_MODE: release

handlers:
- url: /api/.*
  script: auto
  # secure: always

- url: /static
  static_dir: static/build
  # secure: always

- url: /.*
  static_files: static/build/index.html
  upload: static/build/index.html
  # secure: always
