steps:
- name: node
  entrypoint: npm
  dir: 'static'
  args: ['install']
- name: node
  entrypoint: npm
  dir: 'static'
  args: ['run', 'build']
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['app', 'deploy']
timeout: 1600s